name: Linux x86_64 Debug Build

on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: Maximize build space
      uses: typeling1578/maximize-build-space@master
      with:
        root-reserve-mb: 10240
        swap-size-mb: 20480
        remove-dotnet: 'true'
        remove-android: 'true'
        remove-haskell: 'true'

    - uses: actions/checkout@v2

    - name: Setup
      run: |
        cp mozconfigs/gh-actions/linux-x86_64-debug mozconfig

        ./mach bootstrap
        ./tdf-setup --gh-actions

    - name: Build
      run: |
        ./mach build

    - name: Package
      run: |
        ./mach package

    - name: Copy
      run: |
        DISPLAY_VERSION=`cat browser/config/version_display.txt`
        mkdir /home/runner/output
        cp obj-x86_64-pc-linux-gnu/dist/thunderfox-$DISPLAY_VERSION.en-US.linux-x86_64.tar.bz2 /home/runner/output/

    - name: Publish
      uses: actions/upload-artifact@master
      with:
        name: thunderfox-linux-x86_64
        path: /home/runner/output
