name: Linux x86_64 Build

on:
  workflow_dispatch:
  push:
    tags: "*"

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: Setup Disk & Swap Space
      run: |
        echo Before:
        free -h
        df -h

        echo
        echo

        sudo swapoff /mnt/swapfile
        sudo rm /mnt/swapfile
        sudo fallocate -l 10G /mnt/swapfile
        sudo chmod 600 /mnt/swapfile
        sudo mkswap /mnt/swapfile
        sudo swapon /mnt/swapfile

        sudo rm -rf /usr/share/dotnet
        sudo rm -rf /usr/local/lib/android
        sudo rm -rf /opt/ghc

        sudo fallocate -l 10G /home/runner/swapfile2
        sudo chmod 600 /home/runner/swapfile2
        sudo mkswap /home/runner/swapfile2
        sudo swapon /home/runner/swapfile2

        echo
        echo

        echo After:
        free -h
        df -h

    - uses: actions/checkout@v2

    - name: Setup
      run: |
        cp mozconfigs/gh-actions/linux-x86_64 mozconfig

        sudo perl -p -i -e 's%(deb(?:-src|)\s+)https?://(?!archive\.canonical\.com|security\.ubuntu\.com)[^\s]+%$1http://archive.ubuntu.com/ubuntu/%' /etc/apt/sources.list 
        sudo apt update

        sudo apt install xvfb

        ./mach --no-interactive bootstrap --application-choice browser
        ./tdf-setup --gh-actions

    - name: Build
      run: |
        Xvfb :2 -screen 0 1024x768x24 &
        export DISPLAY=:2
        ./mach build

    - name: Package
      run: |
        DISPLAY_VERSION=`cat browser/config/version_display.txt`
        UPDATE_CHANNEL="beta"
        ./mach package
        ./mach package-multi-locale --locales ach af an ar ast az be bg bn br bs ca ca-valencia cak cs cy da de dsb el en-CA en-GB eo es-AR es-CL es-ES es-MX et eu fa ff fi fr fy-NL ga-IE gd gl gn gu-IN he hi-IN hr hsb hu hy-AM ia id is it ja ka kab kk km kn ko lij lt lv mk mr ms my nb-NO ne-NP nl nn-NO oc pa-IN pl pt-BR pt-PT rm ro ru sco si sk sl son sq sr sv-SE szl ta te th tl tr trs uk ur uz vi xh zh-CN zh-TW
        MAR="obj-x86_64-pc-linux-gnu/dist/host/bin/mar" MOZ_PRODUCT_VERSION=$DISPLAY_VERSION MAR_CHANNEL_ID=$UPDATE_CHANNEL ./tools/update-packaging/make_full_update.sh thunderfox-$DISPLAY_VERSION-linux64.mar "obj-x86_64-pc-linux-gnu/dist/thunderfox"

    - name: Copy
      run: |
        DISPLAY_VERSION=`cat browser/config/version_display.txt`
        mkdir /home/runner/output
        cp thunderfox-$DISPLAY_VERSION-linux64.mar /home/runner/output/
        cp obj-x86_64-pc-linux-gnu/dist/thunderfox-$DISPLAY_VERSION.en-US.linux-x86_64.tar.bz2 /home/runner/output/

    - name: Publish
      uses: actions/upload-artifact@master
      with:
        name: thunderfox-linux-x86_64
        path: /home/runner/output
