name: Linux aarch64 Build

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: Set Swap Space
      uses: pierotofy/set-swap-space@master
      with:
        swap-size-gb: 10

    - uses: actions/checkout@v2

    - name: Setup
      run: |
        cp mozconfigs/gh-actions/linux-aarch64 mozconfig

        ./mach bootstrap
        ./tdf-setup --gh-actions

        /home/runner/.cargo/bin/rustup target add aarch64-unknown-linux-gnu

    - name: Build
      run: |
        ./mach build

    - name: Package
      run: |
        DISPLAY_VERSION=`cat browser/config/version_display.txt`
        UPDATE_CHANNEL="beta"
        ./mach package
        ./mach package-multi-locale --locales ach af an ar ast az be bg bn br bs ca ca-valencia cak cs cy da de dsb el en-CA en-GB eo es-AR es-CL es-ES es-MX et eu fa ff fi fr fy-NL ga-IE gd gl gn gu-IN he hi-IN hr hsb hu hy-AM ia id is it ja ka kab kk km kn ko lij lt lv mk mr ms my nb-NO ne-NP nl nn-NO oc pa-IN pl pt-BR pt-PT rm ro ru sco si sk sl son sq sr sv-SE szl ta te th tl tr trs uk ur uz vi xh zh-CN zh-TW
        MAR="obj-aarch64-unknown-linux-gnu/dist/host/bin/mar" MOZ_PRODUCT_VERSION=$DISPLAY_VERSION MAR_CHANNEL_ID=$UPDATE_CHANNEL ./tools/update-packaging/make_full_update.sh thunderfox-$DISPLAY_VERSION-linux_arm64.mar "obj-aarch64-unknown-linux-gnu/dist/thunderfox"

    - name: Copy
      run: |
        DISPLAY_VERSION=`cat browser/config/version_display.txt`
        mkdir /home/runner/output
        cp thunderfox-$DISPLAY_VERSION-linux_arm64.mar /home/runner/output/
        cp obj-aarch64-unknown-linux-gnu/dist/thunderfox-$DISPLAY_VERSION.en-US.linux-aarch64.tar.bz2 /home/runner/output/

    - name: Publish
      uses: actions/upload-artifact@master
      with:
        name: thunderfox-linux-aarch64
        path: /home/runner/output
