name: Windows x64 Build

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: Set Swap Space
      uses: pierotofy/set-swap-space@master
      with:
        swap-size-gb: 10

    - uses: actions/checkout@v2

    - name: Setup
      run: |
        cp mozconfigs/gh-actions/windows-x64-cross mozconfig

        sudo apt install rename

        mkdir /home/runner/win-crosstool
        echo "Downloading clang"
        wget -o null.txt -O /home/runner/win-crosstool/clang.tar.zst https://firefox-ci-tc.services.mozilla.com/api/index/v1/task/gecko.cache.level-3.toolchains.v3.linux64-clang-14.latest/artifacts/public%2Fbuild%2Fclang.tar.zst
        echo "Downloading liblowercase"
        wget -o null.txt -O /home/runner/win-crosstool/liblowercase.tar.zst https://firefox-ci-tc.services.mozilla.com/api/index/v1/task/gecko.cache.level-3.toolchains.v3.linux64-liblowercase.latest/artifacts/public%2Fbuild%2Fliblowercase.tar.zst
        echo "Downloading wine"
        wget -o null.txt -O /home/runner/win-crosstool/wine.tar.zst https://firefox-ci-tc.services.mozilla.com/api/index/v1/task/gecko.cache.level-2.toolchains.v3.linux64-wine.latest/artifacts/public%2Fbuild%2Fwine.tar.zst
        echo "Downloading mar-tools"
        wget -o null.txt -O /home/runner/win-crosstool/mar-tools.tar.zst https://firefox-ci-tc.services.mozilla.com/api/index/v1/task/gecko.cache.level-3.toolchains.v3.linux64-mar-tools.latest/artifacts/public%2Fbuild%2Fmar-tools.tar.zst
        echo "Downloading DIA SDK"
        wget -o null.txt -O "/home/runner/win-crosstool/DIA SDK.zip" ${{ secrets.DIA_SDK_DOWNLOAD_URL }}
        echo "Downloading VC"
        wget -o null.txt -O "/home/runner/win-crosstool/VC.zip" ${{ secrets.VC_DOWNLOAD_URL }}
        echo "Downloading Windows SDK"
        wget -o null.txt -O "/home/runner/win-crosstool/windows-sdk.zip" ${{ secrets.WINDOWS_SDK_DOWNLOAD_URL }}

        echo "Unpacking clang"
        tar -xvf /home/runner/win-crosstool/clang.tar.zst -C /home/runner/win-crosstool > /dev/null 2>&1
        echo "Unpacking liblowercase"
        tar -xvf /home/runner/win-crosstool/liblowercase.tar.zst -C /home/runner/win-crosstool > /dev/null 2>&1
        echo "Unpacking wine"
        tar -xvf /home/runner/win-crosstool/wine.tar.zst -C /home/runner/win-crosstool > /dev/null 2>&1
        echo "Unpacking mar-tools"
        tar -xvf /home/runner/win-crosstool/mar-tools.tar.zst -C /home/runner/win-crosstool > /dev/null 2>&1
        echo "Unpacking DIA SDK"
        unzip "/home/runner/win-crosstool/DIA SDK.zip" -d /home/runner/win-crosstool
        echo "Unpacking VC"
        unzip /home/runner/win-crosstool/VC.zip -d /home/runner/win-crosstool
        echo "Unpacking Windows SDK"
        unzip /home/runner/win-crosstool/windows-sdk.zip -d /home/runner/win-crosstool

        rm /home/runner/win-crosstool/clang.tar.zst
        rm /home/runner/win-crosstool/liblowercase.tar.zst
        rm /home/runner/win-crosstool/wine.tar.zst
        rm /home/runner/win-crosstool/mar-tools.tar.zst
        rm "/home/runner/win-crosstool/DIA SDK.zip"
        rm /home/runner/win-crosstool/VC.zip
        rm /home/runner/win-crosstool/windows-sdk.zip

        # To lower case
        mv /home/runner/win-crosstool/VC /home/runner/win-crosstool/vc
        find /home/runner/win-crosstool/vc -depth -exec rename 's/(.*)\/([^\/]*)/$1\/\L$2/' {} \;
        mv /home/runner/win-crosstool/10 /home/runner/win-crosstool/windows-sdk
        find /home/runner/win-crosstool/windows-sdk -depth -exec rename 's/(.*)\/([^\/]*)/$1\/\L$2/' {} \;
        mv "/home/runner/win-crosstool/DIA SDK" /home/runner/win-crosstool/dia-sdk
        find /home/runner/win-crosstool/dia-sdk -depth -exec rename 's/(.*)\/([^\/]*)/$1\/\L$2/' {} \;
        
        chmod -R +x /home/runner/win-crosstool/dia-sdk
        chmod -R +x /home/runner/win-crosstool/vc
        chmod -R +x /home/runner/win-crosstool/windows-sdk

        ./mach bootstrap
        ./tdf-setup --gh-actions
        /home/runner/.cargo/bin/rustup target add x86_64-pc-windows-msvc
        /home/runner/.cargo/bin/cargo install sccache

    - name: Build
      run: |
        ./mach build

    - name: Package
      run: |
        DISPLAY_VERSION=`cat browser/config/version_display.txt`
        UPDATE_CHANNEL="beta"
        MOZ_CHROME_MULTILOCALE="ach af an ar ast az be bg bn br bs ca ca-valencia cak cs cy da de dsb el en-CA en-GB eo es-AR es-CL es-ES es-MX et eu fa ff fi fr fy-NL ga-IE gd gl gn gu-IN he hi-IN hr hsb hu hy-AM ia id is it ja ka kab kk km kn ko lij lt lv mk mr ms my nb-NO ne-NP nl nn-NO oc pa-IN pl pt-BR pt-PT rm ro ru sco si sk sl son sq sr sv-SE szl ta te th tl tr trs uk ur uz vi xh zh-CN zh-TW"
        for AB_CD in $MOZ_CHROME_MULTILOCALE; do ./mach build chrome-$AB_CD > /dev/null 2>&1; done
        AB_CD=multi ./mach package
        MAR="/home/runner/win-crosstool/mar-tools/mar" MOZ_PRODUCT_VERSION=$DISPLAY_VERSION MAR_CHANNEL_ID=$UPDATE_CHANNEL ./tools/update-packaging/make_full_update.sh thunderfox-$DISPLAY_VERSION-windows64.mar "obj-x86_64-pc-mingw32/dist/thunderfox"

    - name: Copy
      run: |
        DISPLAY_VERSION=`cat browser/config/version_display.txt`
        mkdir /home/runner/output
        cp thunderfox-$DISPLAY_VERSION-windows64.mar /home/runner/output/
        cp obj-x86_64-pc-mingw32/dist/install/sea/thunderfox-$DISPLAY_VERSION.en-US.win64.installer-stub.exe /home/runner/output/
        cp obj-x86_64-pc-mingw32/dist/install/sea/thunderfox-$DISPLAY_VERSION.en-US.win64.installer.exe /home/runner/output/

    - name: Publish
      uses: actions/upload-artifact@master
      with:
        name: thunderfox-windows-x64
        path: /home/runner/output
